# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: 'default'
# pool:
#   vmImage: 'ubuntu-latest'

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'

- task: PackerBuildTest@1
  inputs:
    templateType: 'builtin'
    ConnectedServiceName: 'manual'
    isManagedImage: false
    location: 'southindia'
    storageAccountName: 'diaggarwdiag'
    azureResourceGroup: 'diaggarw'
    baseImageSource: 'default'
    baseImage: 'MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:windows'
    packagePath: 'NodejsApp/NodejsWebApp1'
    deployScriptPath: 'Deploy/windows/deployNodejsApp.ps1'
    imageUri: 'imageUrl'
# - task: PackerBuild@1
#   inputs:
#     templateType: 'builtin'
#     ConnectedServiceName: 'manual'
#     isManagedImage: false
#     location: 'southindia'
#     storageAccountName: 'diaggarwdiag'
#     azureResourceGroup: 'diaggarw'
#     baseImageSource: 'default'
#     baseImage: 'MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:windows'
#     packagePath: 'NodejsApp/NodejsWebApp1'
#     deployScriptPath: 'Deploy/windows/deployNodejsApp.ps1'
#     imageUri: 'imageUrl'

# - task: PackerBuild@0
#   inputs:
#     templateType: 'builtin'
#     ConnectedServiceName: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
#     isManagedImage: false
#     location: 'southindia'
#     storageAccountName: 'diaggarwdiag'
#     azureResourceGroup: 'diaggarw'
#     baseImageSource: 'default'
#     baseImage: 'MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:windows'
#     packagePath: 'NodejsApp/NodejsWebApp1'
#     deployScriptPath: 'Deploy/windows/deployNodejsApp.ps1'
#     imageUri: 'imageUrl'

# - task: PackerBuild@1
#   inputs:
#     templateType: 'builtin'
#     ConnectedServiceName: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
#     isManagedImage: false
#     location: 'eastus2'
#     storageAccountName: 'storageaccountbisha91f6'
#     azureResourceGroup: 'bishalwindedicatedpython'
#     baseImageSource: 'default'
#     baseImage: 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter:windows'
#     packagePath: 'NodejsApp/NodejsWebApp1'
#     deployScriptPath: 'Deploy/windows/deployNodejsApp.ps1'
#     imageUri: 'imageUrl'
# - task: AzureVmssDeployment@0
#   inputs:
#     azureSubscription: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
#     action: 'Configure application startup'
#     vmssName: 'teestPacker'
#     vmssOsType: 'Linux'

# - task: AzureVmssDeployment@0
#   inputs:
#     azureSubscription: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
#     action: 'Configure application startup'
#     vmssName: 'teestPacker'
#     vmssOsType: 'Linux'
#     customScriptsDirectory: '$(System.DefaultWorkingDirectory)' 
#     customScript: 'chmod 0777 script.sh && sh script.sh'
#     customScriptsStorageAccount: 'diaggarwdiag'
# - task: CmdLine@2
#   inputs:
#     script: 'ls -l script.sh'
# - task: AzureVmssDeployment@0
#   inputs:
#     azureSubscription: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
#     action: 'Configure application startup'
#     vmssName: 'testVMSSLinux'
#     vmssOsType: 'Linux'
#     customScriptsDirectory: '$(System.DefaultWorkingDirectory)' 
#     customScript: 'script.sh'
#     customScriptsStorageAccount: 'diaggarwdiag'

# - task: AzureVmssDeployment@0 
#   displayName: 'Deploy custom script application' 
#   inputs: 
#     azureSubscription: 'Deploy a custom script app on VMSS Agents-Dev - 1 - Azure' 
#     action: 'Configure application startup' 
#     vmssName: 'Agents-Dev' 
#     vmssOsType: Linux 
#     customScriptsDirectory: '$(System.DefaultWorkingDirectory)' 
#     customScript: 'sh script.sh'
#     customScriptsStorageAccount: customscriptagents
