# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'

- task: PackerBuild@1
  inputs:
    templateType: 'builtin'
    ConnectedServiceName: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
    isManagedImage: false
    location: 'eastus2'
    storageAccountName: 'storageaccountbisha91f6'
    azureResourceGroup: 'bishalwindedicatedpython'
    baseImageSource: 'default'
    baseImage: 'MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:windows'
    packagePath: 'NodejsApp/NodejsWebApp1'
    deployScriptPath: 'Deploy/windows/deployNodejsApp.ps1'
    imageUri: 'imageUrl'
